Repository textlint-ja/textlint-rule-preset-ai-writing, pull requests merged in 2025-07, with the labels that each got.

#17 feat: add no-ai-colon-continuation rule with kuromojin morphological analysis
  README.md
  package-lock.json
  package.json
  src/index.ts
  src/rules/ai-tech-writing-guideline.ts
  src/rules/no-ai-colon-continuation.ts
  test/rules/ai-tech-writing-guideline.test.ts
  test/rules/no-ai-colon-continuation.test.ts
Labels: Type: Feature

#18 Improve error
  src/rules/no-ai-colon-continuation.ts
  test/rules/no-ai-colon-continuation.test.ts
Labels: Type: Refactoring

#21 feat: Biomeを導入してPrettierを置き換え
  .githooks/pre-commit
  .textlintrc.json
  biome.json
  package-lock.json
  package.json
  src/index.ts
  src/rules/ai-tech-writing-guideline.ts
  src/rules/no-ai-colon-continuation.ts
  src/rules/no-ai-emphasis-patterns.ts
  src/rules/no-ai-hype-expressions.ts
  src/rules/no-ai-list-formatting.ts
  tsconfig.json
Labels: Type: Maintenance

#22 見出し内の太字パターン（との両方）を検出
  README.md
  package-lock.json
  src/rules/no-ai-emphasis-patterns.ts
  test/rules/no-ai-emphasis-patterns.test.ts
Labels: Type: Feature
